Add bug id to changelog of pillar example fix
SUSE/habootstrap-formula pull request #55
Opened 2020-08-27 14:43 UTC by Simranpal

Add missing bugzilla reference for fix. Related to https://github.com/SUSE/habootstrap-formula/pull/54

2020-08-27 14:45 UTC, MalloZup commented on habootstrap-formula.changes
> +  (bsc#1174994)
afaik you can put it on same line.

2020-08-27 14:45 UTC, arbulu89 approved these changes

2020-08-27 15:09 UTC, MalloZup approved these changes
i'm ok too. I used to put bsc number inline but there is not strong convention there

2020-08-31 06:10 UTC, arbulu89 requested changes
@Simranpal I will request changes to fix the folder where the `pillar.example` file is stored. I would store it in the `doc` folder

2020-09-14 18:48 UTC, Simranpal commented
> @Simranpal I will request changes to fix the folder where the `pillar.example` file is stored. I would store it in the `doc` folder

As discussed in the other PR, placing it in `metadata` directory

2020-09-15 06:42 UTC, arbulu89 approved these changes

2020-09-15 23:12 UTC, merged