Cluster not initialized
SUSE/habootstrap-formula pull request #85
Opened 2021-08-23 21:58 UTC by yeoldegrove

This fixes https://github.com/SUSE/ha-sap-terraform-deployments/issues/713.

If resources or cluster properties are applied too fast on first node such actions will fail.
The reason is, that the node might still be in `UNCLEAN` state.
e.g.
```
2021-06-14 13:19:31,506 [salt.loaded.int.module.cmdmod:395 ][INFO    ][4417] Executing command '/usr/sbin/crm' in directory '/root'
2021-06-14 13:19:31,981 [salt.loaded.int.module.cmdmod:836 ][ERROR   ][4417] Command '/usr/sbin/crm' failed with return code: 1
2021-06-14 13:19:31,982 [salt.loaded.int.module.cmdmod:838 ][ERROR   ][4417] stdout: Could not connect to the CIB: Transport endpoint is not connected
crm_mon: Error: cluster is not available on this node
ERROR: status: crm_mon (rc=102):
2021-06-14 13:19:31,982 [salt.loaded.int.module.cmdmod:842 ][ERROR   ][4417] retcode: 1
2021-06-14 13:19:31,983 [salt.state       :323 ][ERROR   ][4417] Cluster is not created yet. Run cluster_initialized before
2021-06-14 13:19:31,983 [salt.state       :2063][INFO    ][4417] Completed state [update] at time 13:19:31.983469 (duration_in_ms=478.278)
2021-06-14 13:19:31,984 [salt.state       :1881][INFO    ][4417] Running state [configure-cluster-properties] at time 13:19:31.984224
2021-06-14 13:19:31,984 [salt.state       :1914][INFO    ][4417] Executing state crm.cluster_properties_present for [configure-cluster-properties]
2021-06-14 13:19:31,986 [salt.loaded.int.module.cmdmod:395 ][INFO    ][4417] Executing command '/usr/sbin/crm' in directory '/root'
```

A simple workaround is to add another wait (same one that is already done on the joining nodes).
This should do no harm and only marginally increases the deployment time.

#76 might include an alternative approach but is not ready to be merged yet.

2021-08-24 07:50 UTC, angelabriel approved these changes
From my point of view it is okay as a temporary workaround to get the deployments work again now.
But the final solution should be in sync with the solution of https://github.com/SUSE/habootstrap-formula/pull/76, so that we can get rid of the 'sleeps'.
@arbulu89 it would be nice, if you can take this change into account, when you finish the work on https://github.com/SUSE/habootstrap-formula/pull/76

2021-08-24 10:32 UTC, petersatsuse commented
I see this too for node1, but after node2 is there, the cluster and hana look full functional - but the "terraform" break with a error and does not finish with the normal display of the output variables.
I used version 7.0.0 with v7 packages and hana 51053381

As the error shows up the cluster error at node1 at the time where node2 the cluster is still not up, its could be a false positive.
But the problem is that later the state errors let the whole deployment fail with an error.

What puzzles me is that 
- after logging in to the node hana1, all is good. The cluster and the systemreplicaton are fine and running.
- it had worked before for sure
- i used the same v7 packages, but it looks like something has changed there as the error comes from the formulas
- as the v7 packages come in on demand, there is no control and hint if they change (which they should not)

Could there be took some additional effort to provide a stable baseline to have valid deployments.

2021-08-24 11:26 UTC, yeoldegrove commented
> * after logging in to the node hana1, all is good. The cluster and the systemreplicaton are fine and running.

This is because shortly after the hana1 deployments fails, the resoures are also configred by salt on hana2 which is successfull, as all nodes are `ONLINE` at this point in time (and not `UNCLEAN` [initializing]).

> * it had worked before for sure
> * i used the same v7 packages, but it looks like something has changed there as the error comes from the formulas
> * as the v7 packages come in on demand, there is no control and hint if they change (which they should not)

@petersatsuse Can you elaborate what "v7 packages" means?

2021-08-24 13:30 UTC, petersatsuse commented
> @petersatsuse Can you elaborate what "v7 packages" means?

The repository for the packages which should work with the tagged version of the project.
e.g. ha_sap_deployment_repo = "https://download.opensuse.org/repositories/network:/ha-clustering:/sap-deployments:/v7/"

The ha-sap-terraform-deployments project tagged 7.x.x should work with the rpm packages from .../sap-deployments:/v7/"

2021-08-30 09:51 UTC, arbulu89 requested changes
@yeoldegrove ,
I don't really like this workaround (even though it would work).
What we should do instead is to assure the the cluster initialization finishes when the cluster is up and running. We should check within the cluster initilization code, and make this happen.
It might require some changes in the `salt-shaptools` project, but it's worth having a look

2021-08-30 09:51 UTC, arbulu89 commented on cluster/init.sls
> +{% if cluster.init == host %}
Is intentional to have this within the `if cluster.corosync is defined` condition?

2021-08-30 09:53 UTC, arbulu89 commented
> I see this too for node1, but after node2 is there, the cluster and hana look full functional - but the "terraform" break with a error and does not finish with the normal display of the output variables.
> I used version 7.0.0 with v7 packages and hana 51053381
> 
> As the error shows up the cluster error at node1 at the time where node2 the cluster is still not up, its could be a false positive.
> But the problem is that later the state errors let the whole deployment fail with an error.
> 
> What puzzles me is that
> 
>     * after logging in to the node hana1, all is good. The cluster and the systemreplicaton are fine and running.
> 
>     * it had worked before for sure
> 
>     * i used the same v7 packages, but it looks like something has changed there as the error comes from the formulas
> 
>     * as the v7 packages come in on demand, there is no control and hint if they change (which they should not)
> 
> 
> Could there be took some additional effort to provide a stable baseline to have valid deployments.

@petersatsuse Without removing any responsability to us, keep in mind that this projects and the success of a deployment doesn't only relay on this code, it depends in many many things (changes in the cloud infrastructure, in the cloud images, in any package shipped by suse, in any change in the cluster). Maybe the error comes from some point that we don't even have any control, or some change that is not based in this project.

2021-09-08 11:45 UTC, yeoldegrove commented
closed in favor of #86

2021-09-08 11:45 UTC, closed without merging